### ISSUE TITLE
Akú databázu použijeme?

### ISSUE THREAD

**Issue by pandula3** [TIS2016/MeracieZariadenia#15]
postgresql? sql lite?

**Comment by Larcele** [comment]
https://www.digitalocean.com/community/tutorials/sqlite-vs-mysql-vs-postgresql-a-comparison-of-relational-database-management-systems

https://www.reddit.com/r/rails/comments/44ki6e/whats_the_difference_between_choosing_sqlite_vs/

celkom fajn thready na precitanie/zamyslenie sa...ja sa priklanam zatial k SQLite
