### ISSUE TITLE
Upraviť stavový diagram

### ISSUE THREAD

**Issue by fackovcova5** [TIS2016/MeracieZariadenia#17]
- zobrazenie online odstrániť lebo to tam nepatrí
- dopytujúci čo robí - pošle do databázy alebo čo, skôr by sa mal nachádzať na lokálnej časti, skôr by sa mal volať čakajúci na dopyt, hľadá na serveri dáta (stavy - načíta, ukladá a potom sa vráti späť)

**Comment by wendl4** [comment]
druhy bod este treba zapracovat
